<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<link rel="shortcut icon" href="http://zhaopin.weichg.com/favicon.ico" />
<title>微城</title>
<script language="javascript" src="http://zhaopin.weichg.com/js/jquery-min.js"></script>
<style type="text/css">
body {
	font-size: 13px;	
}
#Header {
	width: 80%;
	margin-top: 20px;
	margin-right: 10%;
	margin-left: 10%;
	height: auto;
	margin-bottom: 2px;
	clear: both;
}
#Logo {
}
#Navi {
	background-color: #DB061C;
	height: 36px;
}
#Navi ul {
	list-style-type: none;
}
#Navi li {
	list-style-type: none;
	float: left;
	margin: 10px;
}
#Navi li a {
	text-decoration:none;
	color:#000;
}

#Content {
	margin-top: 5px;
	margin-right: 10%;
	margin-bottom: 20px;
	margin-left: 10%;
	clear: both;
	font-size: 14px;
}
#Ad {
	margin-bottom: 20px;
	text-align: center;
	margin-right: 10%;
	margin-left: 10%;
	clear: both;
}
#Ad img{
	width:980px;
	text-align: center;
	clear: both;
}
#RegionTitle {
	text-align:center;
	font-size:20px;
}
#Region {
	float: left;
	margin-top: 20px;
}
#Region ul {
	list-style-type: none;
	margin-left: 10px;
}
#Region ul.level1 {
	list-style-type: none;
	margin-left: 0px;
}
#Region li {
	list-style-type: none;
	margin: 5px;
	padding: 5px;
}
#Region li a {
	text-decoration:none;
	color:#000;
}

/*#Region li:link{
	background-color:#000;
}
#Region li:visited{
	background-color:#000;
}
#Region li:hover{
	background-color: #DB061C;
}*/
#Region .jiaru {
    height:40px;
    width: 120px;
    border-style:none;
	padding:8px 30px;
	line-height:24px;
	color:#fff;
	font:16px "Microsoft YaHei", Verdana, Geneva, sans-serif;
	cursor:pointer;
	/*border:1px #ae7d0a solid;*/
	-webkit-box-shadow:inset 0px 0px 1px #fff;
	-moz-box-shadow:inset 0px 0px 1px #fff;
	box-shadow:inset 0px 0px 1px #fff;
	/*-webkit-border-radius:4px;
	-moz-border-radius:4px;
	border-radius:4px;
	text-shadow:1px 1px 0px #b67f01;/*字体阴影效果*/
	background-color:#DB061C;
}

#Region p {
	line-height: 20px;
}

#Region p.level2 {
	line-height: 25px;
	margin-left:25px;
}
#Footer {
	width: 80%;
	margin-top: 20px;
	margin-right: 10%;
	margin-bottom: 20px;
	margin-left: 10%;
	clear: both;
}
</style>
</head>

<body>
<div id="Header">
<div id="Logo">
  <div><a href="../"><img src="http://zhaopin.weichg.com/images/logo.png" width="173" height="72"></a></div>
</div>
<div id="Navi"><ul>
  <li><a href="http://zhaopin.weichg.com">首页</a></li>
  <li><a href="http://zhaopin.weichg.com/about/">关于微城</a></li>
  <li><a href="http://zhaopin.weichg.com/hr/">人才招聘</a></li>
  <li><a href="http://zhaopin.weichg.com/about/link/">联系我们</a></li>
</ul></div>
</div>
<div id="Ad"><img src="http://zhaopin.weichg.com/images/ad.gif" height="200"></div>
<div id=Content>
<div id="RegionTitle"><strong>微城暑期兼职招聘公告</strong></div>
<div id="Region">
  <p>“春雨计划”<br>
&nbsp;&nbsp;&nbsp;&nbsp;网商的兴盛带来了便捷，同时也带来了诸多问题：用户体验、商品投诉、售后服务、返退返修等等。实体店在这些消费者利益问题面前，具有天生的优势。因此，微城希望通过帮助实体店转型升级，带给消费者更好的消费体验。微城第一个改造的是母婴行业实体店，在全国各县城母婴店中选择一个合适的合作伙伴，在实体店前期资金和人力双零投入的情况下，完成对这些实体店的改造，转型为线上线下综合销售、服务的移动互联网商业模式。<br>
&nbsp;&nbsp;&nbsp;&nbsp;春雨计划号召在校大学生回到家乡去，通过暑假时间利用自身知识帮助广阔的全国1000个县城、乡镇的母婴店完成上述转型，增强综合竞争力从而更好的服务于孕婴童，使得母婴行业得以春雨般的滋润。大学生有知识、有理想、有报效社会的意愿，同时暑假中有时间、有能力完成这一壮举。 另一方面，微城希望借此给广大有志向的大学生，一个提早体验、学习、探索商业社会中的相关知识和门道，为将来毕业积累宝贵的实践经验，并可以得到一定的报酬。这也是微城对象牙塔播撒的另一场春雨，为种子的未来储存力量。<br>
&nbsp;&nbsp;&nbsp;&nbsp;来吧，让全国的实体店接受春雨的洗礼，非你不可。let's go!<br>
  </p>
    <p><strong>招聘岗位：</strong></p>
    <p class="level2"><strong>市场推广员200名</strong><br>
    <p class="level2"><strong>工作内容：</strong><ul>
      <li>1. 给实体店经营者介绍网上商城（微城）。</li>
      <li>2. 与实体店签订微城免费试用协议，并培训其使用方法。</li>
      <li>3. 帮助实体店体验一次网上团购、采购业务。</li>
      <li>4. 收集、登记实体店的基本情况。	</li></ul>
    <p class="level2"><strong>待遇：</strong> 2900—5400元。</p>
    <p class="level2"><strong>电商指导员200名</strong><br>
    <p class="level2"><strong>工作内容：</strong><ul>
      <li>1. 给实体店经营者介绍网上商城（微城）。</li>
      <li>2. 与实体店签订微城免费试用协议，并培训其使用方法。</li>
      <li>3. 帮助实体店体验一次网上团购、采购业务。</li>
      <li>4. 收集、登记实体店的基本情况。	</li>
      <li>5. 收取实体店首笔商城使用费300元。</li></ul>
	<p class="level2"><strong>待遇：</strong> 3900—7400元。</p>
    <p><strong>工作地点：</strong>各自家乡所在地及其周边县城（5个）。【可报名挑战更多工作量】<br></p>
      <p><strong>工作时间：</strong>2014.7.1—2014.8.15， 工作时长由能力决定，按标准完成即可</p>
    <p><strong>工资支付方式：</strong><ul>
              <li>1. 出发前预支200元/人</li>
              <li>2. 每完成一家实体店的上述工作内容，即汇款500元/家 或700元/家。</li></ul>
    <p><strong>招聘说明：</strong><ul>
      <li>1.公司将对所有人员统一进行2天免费培训【销售与沟通、陌生拜访、产品知识等】，以保障参与人员达到预期工作成果。</li>
      <li>2.所有人员统一购买20万元意外险。</li>
      <li>3.设立PK基金：1等奖1人5000元，2等奖2人各3000元，3等奖5人各1000元，优秀奖10人各100元礼品。所有获奖者荣誉证书一本。【获奖者下次再兼职时，工资加100元】</li>
      <li>4.差旅费用实报实销。</li></ul>
    <p><strong>招聘要求：</strong><ul>
      <li>1.有志者。</li>
      <li>2.自备笔记本电脑一台【保管责任自负】。</li></ul>
    <p><strong>报名时间：</strong>2014年6月25日 晚23:59:59止<br></p>
      <p><strong>报名方式：</strong>点击下面“我要报名”</p>
    <p><input name="" type="button" class="jiaru" onClick="window.location.href='../hr/'" value="我要报名"></p>
  <p>&nbsp;</p>
</div>
</div>
<div id=Footer>
  Copyright &copy; 2014 微城网络科技
</div>

</body>
</html>