<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<link rel="shortcut icon" href="http://zhaopin.weichg.com/favicon.ico" />
<title>微城</title>
<script language="javascript" src="http://zhaopin.weichg.com/js/jquery-min.js"></script>
<style type="text/css">
body {
	font-size: 13px;	
}
#Header {
	width: 80%;
	margin-top: 20px;
	margin-right: 10%;
	margin-left: 10%;
	height: auto;
	margin-bottom: 2px;
	clear: both;
}
#Logo {
}
#Navi {
	background-color: #DB061C;
	height: 36px;
}
#Navi ul {
	list-style-type: none;
}
#Navi li {
	list-style-type: none;
	float: left;
	margin: 10px;
}
#Navi li a {
	text-decoration:none;
	color:#000;
}

#Content {
	margin-top: 5px;
	margin-right: 10%;
	margin-bottom: 20px;
	margin-left: 10%;
	clear: both;
	font-size: 14px;
}
#Ad {
	margin-bottom: 20px;
	text-align: center;
	margin-right: 10%;
	margin-left: 10%;
	clear: both;
}
#Ad img{
	width:980px;
	text-align: center;
	clear: both;
}
#RegionTitle {
	text-align:center;
	font-size:20px;
}
#Region {
	float: left;
	margin-top: 20px;
}
#Region ul {
	list-style-type: none;
	padding-left: 25px;
}
#Region li {
	list-style-type: none;
	margin: 5px;
	padding: 5px;
}
#Region li a {
	text-decoration:none;
	color:#000;
}

/*#Region li:link{
	background-color:#000;
}
#Region li:visited{
	background-color:#000;
}
#Region li:hover{
	background-color: #DB061C;
}*/
#Region .jiaru {
    height:40px;
    width: 120px;
    border-style:none;
	padding:8px 30px;
	line-height:24px;
	color:#fff;
	font:16px "Microsoft YaHei", Verdana, Geneva, sans-serif;
	cursor:pointer;
	/*border:1px #ae7d0a solid;*/
	-webkit-box-shadow:inset 0px 0px 1px #fff;
	-moz-box-shadow:inset 0px 0px 1px #fff;
	box-shadow:inset 0px 0px 1px #fff;
	/*-webkit-border-radius:4px;
	-moz-border-radius:4px;
	border-radius:4px;
	text-shadow:1px 1px 0px #b67f01;/*字体阴影效果*/
	background-color:#DB061C;
}

#Region p {
	line-height: 20px;
	font-size:14px;
}

#Region p.level2 {
	line-height: 25px;
	margin-left:25px;
}
#Footer {
	width: 80%;
	margin-top: 20px;
	margin-right: 10%;
	margin-bottom: 20px;
	margin-left: 10%;
	clear: both;
}
</style>
</head>

<body>
<div id="Header">
<div id="Logo">
  <div><a href="../"><img src="http://zhaopin.weichg.com/images/logo.png" width="173" height="72"></a></div>
</div>
<div id="Navi"><ul>
  <li><a href="http://zhaopin.weichg.com">首页</a></li>
  <li><a href="http://zhaopin.weichg.com/about/">关于微城</a></li>
  <li><a href="http://zhaopin.weichg.com/hr/">人才招聘</a></li>
  <li><a href="http://zhaopin.weichg.com/about/link/">联系我们</a></li>
</ul></div>
</div>
<div id="Ad"><img src="http://zhaopin.weichg.com/images/ad.gif" height="200"></div>
<div id=Content>
<div id="RegionTitle"><strong>关于微城</strong></div>
<div id="Region">
  <p>&nbsp;&nbsp;&nbsp;&nbsp;
  湘潭经天信息化技术服务有限公司是一家网络科技企业，于08年8月8日成立，服务了数百家本地中小企业。2014年，随着移动互联网的浪潮迭起，经天组建一支专业团队耗时6个月打造出了&ldquo;微城&rdquo;新模式。微城是一种全新的基于移动互联网的商业模式，通过移动互联网技术上连厂商，中连实体店铺，下连消费者的方式提供给实体店的一个全新运作平台。<br>
    &nbsp;&nbsp;&nbsp;&nbsp; 由于网络购物的兴起，传统实体店生存空间被压缩，微城希望通过自有平台扶持部分实体店在局部范围内拥有和淘宝、京东一战的能力,并跟上电子商务化的浪潮，以获得未来稳固发展的根基。  
  <p><br>
  <p><strong>企业愿景：</strong> 打造全新的移动互联网商业模式<br></p>
    <p><strong>经营理念：</strong> 创新----走不一样的路<br></p>
    <p><strong>微城精神：</strong> 服务创造价值</p>
    <p></p>
  <p>&nbsp;</p>
</div>
</div>
<div id=Footer>
  Copyright &copy; 2014 微城网络科技
</div>

</body>
</html>