<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<link rel="shortcut icon" href="http://zhaopin.weichg.com/favicon.ico" />
<title>微城</title>
<script language="javascript" src="http://zhaopin.weichg.com/js/jquery-min.js"></script>
<style type="text/css">
body {
	font-size: 13px;	
}
#Header {
	width: 80%;
	margin-top: 20px;
	margin-right: 10%;
	margin-left: 10%;
	height: auto;
	margin-bottom: 2px;
	clear: both;
}
#Logo {
}
#Navi {
	background-color: #DB061C;
	height: 36px;
}
#Navi ul {
	list-style-type: none;
}
#Navi li {
	list-style-type: none;
	float: left;
	margin: 10px;
}
#Navi li a {
	text-decoration:none;
	color:#000;
}

#Content {
	margin-top: 5px;
	margin-right: 10%;
	margin-bottom: 20px;
	margin-left: 10%;
	clear: both;
	font-size: 14px;
}
#Ad {
	margin-bottom: 20px;
	text-align: center;
	margin-right: 10%;
	margin-left: 10%;
	clear: both;
}
#Ad img{
	width:980px;
	text-align: center;
	clear: both;
}
#RegionTitle {
	text-align:center;
	font-size:20px;
}
#Region {
	float: left;
	margin-top: 20px;
}
#Region ul {
	list-style-type: none;
	padding-left: 25px;
}
#Region li {
	list-style-type: none;
	margin: 5px;
	padding: 5px;
}
#Region li a {
	text-decoration:none;
	color:#000;
}

/*#Region li:link{
	background-color:#000;
}
#Region li:visited{
	background-color:#000;
}
#Region li:hover{
	background-color: #DB061C;
}*/
#Region .jiaru {
    height:40px;
    width: 120px;
    border-style:none;
	padding:8px 30px;
	line-height:24px;
	color:#fff;
	font:16px "Microsoft YaHei", Verdana, Geneva, sans-serif;
	cursor:pointer;
	/*border:1px #ae7d0a solid;*/
	-webkit-box-shadow:inset 0px 0px 1px #fff;
	-moz-box-shadow:inset 0px 0px 1px #fff;
	box-shadow:inset 0px 0px 1px #fff;
	/*-webkit-border-radius:4px;
	-moz-border-radius:4px;
	border-radius:4px;
	text-shadow:1px 1px 0px #b67f01;/*字体阴影效果*/
	background-color:#DB061C;
}

#Region p {
	line-height: 20px;
	font-size:14px;
}

#Region p.level2 {
	line-height: 25px;
	margin-left:25px;
}
#Footer {
	width: 80%;
	margin-top: 20px;
	margin-right: 10%;
	margin-bottom: 20px;
	margin-left: 10%;
	clear: both;
}
</style>
</head>

<body>
<div id="Header">
<div id="Logo">
  <div><a href="../"><img src="http://zhaopin.weichg.com/images/logo.png" width="173" height="72"></a></div>
</div>
<div id="Navi"><ul>
  <li><a href="http://zhaopin.weichg.com">首页</a></li>
  <li><a href="http://zhaopin.weichg.com/about/">关于微城</a></li>
  <li><a href="http://zhaopin.weichg.com/hr/">人才招聘</a></li>
  <li><a href="http://zhaopin.weichg.com/about/link/">联系我们</a></li>
</ul></div>
</div>
<div id="Ad"><img src="http://zhaopin.weichg.com/images/ad.gif" height="200"></div>
<div id=Content>
<div id="RegionTitle"><strong>联系我们</strong></div>
<div id="Region">
  <p class="level2"><strong>公司：</strong> 湘潭经天信息化技术服务有限公司
  <p class="level2"><strong>地址：</strong> 湘潭市岳塘区建设中路422号<br></p>
   <p class="level2"> <strong>联系人：</strong> 周经理<br></p>
   <p class="level2"> <strong>联系电话：</strong>18975258850<br></p>
   <p class="level2"> <strong>邮箱：</strong> zhaopin@weichg.com</p>
<p></p>
  <p>&nbsp;</p>
</div>
</div>
<div id=Footer>
  Copyright &copy; 2014 微城网络科技
</div>

</body>
</html>